// Top Sales
export const FETCH_TOP_SALES_REQUEST = "FETCH_TOP_SALES_REQUEST";
export const FETCH_TOP_SALES_ERROR = "FETCH_TOP_SALES_ERROR";
export const FETCH_TOP_SALES_SUCCESS = "FETCH_TOP_SALES_SUCCESS";

// Tab Menu
export const FETCH_TAB_MENU_REQUEST = "FETCH_TAB_MENU_REQUEST";
export const FETCH_TAB_MENU_ERROR = "FETCH_TAB_MENU_ERROR";
export const FETCH_TAB_MENU_SUCCESS = "FETCH_TAB_MENU_SUCCESS";
export const CHANGE_ACTIVE_TAB = "CHANGE_ACTIVE_TAB";

// Product List
export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const RESPONSE_PRODUCTS_AMOUNT = "RESPONSE_PRODUCTS_AMOUNT";

// Load more products
export const LOAD_MORE_PRODUCTS_REQUEST = "LOAD_MORE_PRODUCTS_REQUEST";
export const LOAD_MORE_PRODUCTS_ERROR = "LOAD_MORE_PRODUCTS_ERROR";
export const LOAD_MORE_PRODUCTS_SUCCESS = "LOAD_MORE_PRODUCTS_SUCCESS";

// Search
export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

// Product Card
export const FETCH_PRODUCT_CARD_REQUEST = "FETCH_PRODUCT_CARD_REQUEST";
export const FETCH_PRODUCT_CARD_ERROR = "FETCH_PRODUCT_CARD_ERROR";
export const FETCH_PRODUCT_CARD_SUCCESS = "FETCH_PRODUCT_CARD_SUCCESS";
export const SELECT_PRODUCT_SIZE = "SELECT_PRODUCT_SIZE";
export const QUANTITY_PRODUCT_ADD = "QUANTITY_PRODUCT_ADD";
export const QUANTITY_PRODUCT_DEL = "QUANTITY_PRODUCT_DEL";

// Cart
export const ADD_PRODUCT_TO_BASKET = "ADD_PRODUCT_TO_BASKET";
export const REMOVE_PRODUCT_FROM_BASKET = "REMOVE_PRODUCT_FROM_BASKET";
export const CALC_TOTAL_AMOUNT = "CALC_TOTAL_AMOUNT";

// Order Form
export const CART_ORDER_CHANGE_FIELD = "CART_ORDER_CHANGE_FIELD";
export const FETCH_ORDER_REQUEST = "FETCH_ORDER_REQUEST";
export const FETCH_ORDER_ERROR = "FETCH_ORDER_ERROR";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const CLEAR_BASKET = "CLEAR_BASKET";
export const CLEAR_RESPONSE = "CLEAR_RESPONSE";